CREATE DATABASE LOGIN_SYSTEM;

CREATE TABLE USERS(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
USER_ID BIGINT, 
USER_NAME VARCHAR(100),
PASSWORD VARCHAR(100),
DATE TIMESTAMP,
INDEX INDEX_USER_ID_USER_NAME_DATE(USER_ID,USER_NAME,DATE)    
);